import fs from 'node:fs';
import assert from 'node:assert/strict';
const path = 'apps/mobile/public/spots-catalog.json';
const raw = fs.readFileSync(path, 'utf8');
const before = JSON.parse(raw);
const next = structuredClone(before);
const spot = next.spots.find(s => s.id === 3688 && s.slug === 'buddies-burger');
const branch = next.branches.find(b => b.id === 5249 && b.spot_id === 3688);
assert(spot && branch);
spot.is_active = true;
branch.is_active = true;
assert.equal(spot.catalog_status, 'needs_info');
const restored = structuredClone(next);
restored.spots.find(s => s.id === 3688).is_active = before.spots.find(s => s.id === 3688).is_active;
restored.branches.find(b => b.id === 5249).is_active = before.branches.find(b => b.id === 5249).is_active;
assert.deepEqual(restored, before);
assert.equal(fs.readFileSync(path, 'utf8'), raw, 'Concurrent edit');
fs.writeFileSync(path, JSON.stringify(next, null, 2) + '\n');
assert.deepEqual(JSON.parse(fs.readFileSync(path, 'utf8')), next);
console.log('Only Buddies spot and branch visibility changed; needs_info preserved.');
