-- Canonical schema v2
-- Base de datos primero: una sola fuente de verdad para app y admin.
-- Estructura:
--   public.spots                           -> entidad principal (lugar o parche)
--   public.spot_branches                   -> sedes / ubicaciones operativas
--   public.spot_branch_hours               -> horario semanal base por sede
--   public.spot_branch_schedule_exceptions -> excepciones por fecha / festivos
--   public.spot_likes                      -> likes por usuario sobre el spot principal

create table if not exists public.spots (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('place', 'event')),
  slug text not null unique,
  name text not null,
  short_description text not null default '',
  cover_image_url text not null default '',
  gallery_urls text[] not null default '{}',
  category text not null,
  city text not null default 'Cali',
  likes text not null default '0',
  tags text[] not null default '{}',
  moods text[] not null default '{}',
  is_active boolean not null default true,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists spots_v2_type_idx on public.spots (type);
create index if not exists spots_v2_category_idx on public.spots (category);
create index if not exists spots_v2_active_idx on public.spots (is_active);

create table if not exists public.spot_branches (
  id bigint generated by default as identity primary key,
  spot_id bigint not null references public.spots (id) on delete cascade,
  slug text not null unique,
  neighborhood text not null default '',
  mall text not null default '',
  -- Mantener hours como campo editorial/derivado mientras migramos la app.
  hours text not null default '',
  holiday_mode text not null default 'inherit'
    check (holiday_mode in ('inherit', 'same_as_sunday', 'closed', 'custom')),
  holiday_open_time time,
  holiday_close_time time,
  holiday_split_open_time time,
  holiday_split_close_time time,
  address text not null default '',
  min_budget integer not null default 0,
  max_people integer not null default 1,
  menu_url text not null default '',
  whatsapp text not null default '',
  phone text not null default '',
  instagram text not null default '',
  latitude double precision,
  longitude double precision,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists spot_branches_spot_idx on public.spot_branches (spot_id);
create index if not exists spot_branches_active_idx on public.spot_branches (is_active);
create index if not exists spot_branches_sort_idx on public.spot_branches (sort_order);

create table if not exists public.spot_branch_hours (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.spot_branches (id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  is_closed boolean not null default false,
  open_time time,
  close_time time,
  split_open_time time,
  split_close_time time,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, day_of_week)
);

create index if not exists spot_branch_hours_branch_idx on public.spot_branch_hours (branch_id);
create index if not exists spot_branch_hours_day_idx on public.spot_branch_hours (day_of_week);

create table if not exists public.spot_branch_schedule_exceptions (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.spot_branches (id) on delete cascade,
  exception_date date not null,
  is_closed boolean not null default false,
  open_time time,
  close_time time,
  split_open_time time,
  split_close_time time,
  label text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, exception_date)
);

create index if not exists spot_branch_schedule_exceptions_branch_idx
  on public.spot_branch_schedule_exceptions (branch_id);
create index if not exists spot_branch_schedule_exceptions_date_idx
  on public.spot_branch_schedule_exceptions (exception_date);

alter table public.spots replica identity full;
alter table public.spot_branches replica identity full;
alter table public.spot_branch_hours replica identity full;
alter table public.spot_branch_schedule_exceptions replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'spots'
  ) then
    execute 'alter publication supabase_realtime add table public.spots';
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'spot_branches'
  ) then
    execute 'alter publication supabase_realtime add table public.spot_branches';
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'spot_branch_hours'
  ) then
    execute 'alter publication supabase_realtime add table public.spot_branch_hours';
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'spot_branch_schedule_exceptions'
  ) then
    execute 'alter publication supabase_realtime add table public.spot_branch_schedule_exceptions';
  end if;
end $$;

create table if not exists public.spot_likes (
  user_id uuid not null references auth.users (id) on delete cascade,
  spot_id bigint not null references public.spots (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, spot_id)
);

create index if not exists spot_likes_v2_spot_idx on public.spot_likes (spot_id);
create index if not exists spot_likes_v2_user_idx on public.spot_likes (user_id);

alter table public.spot_likes enable row level security;
alter table public.spot_likes replica identity full;

create policy "public read spot likes"
on public.spot_likes
for select
to anon, authenticated
using (true);

create policy "authenticated manage own likes"
on public.spot_likes
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

alter publication supabase_realtime add table public.spot_likes;
