create table if not exists public.place_suggestions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  submitted_by_user_id uuid references auth.users (id) on delete set null,
  submitted_by_name text not null default '',
  submitted_by_email text not null default '',
  source text not null default 'explore',
  status text not null default 'pending'
    check (status in ('pending', 'reviewed', 'imported', 'discarded')),
  suggested_places text[] not null default '{}',
  suggested_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists place_suggestions_created_at_idx
  on public.place_suggestions (created_at desc);

create index if not exists place_suggestions_status_idx
  on public.place_suggestions (status);

create index if not exists place_suggestions_user_idx
  on public.place_suggestions (submitted_by_user_id);

alter table public.place_suggestions enable row level security;

create policy "public insert place suggestions"
on public.place_suggestions
for insert
to anon, authenticated
with check (true);

create policy "authenticated read own place suggestions"
on public.place_suggestions
for select
to authenticated
using (
  submitted_by_user_id = auth.uid()
  or submitted_by_email = coalesce(auth.jwt() ->> 'email', '')
);

create policy "service role manage place suggestions"
on public.place_suggestions
for all
to service_role
using (true)
with check (true);

comment on table public.place_suggestions is
  'Sugerencias manuales de lugares enviadas desde la app para revisarlas y subirlas luego por bloques o por fecha.';
