create table if not exists public.feedback_notes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  submitted_by_user_id uuid references auth.users (id) on delete set null,
  submitted_by_name text not null default '',
  submitted_by_email text not null default '',
  source text not null default 'explore',
  status text not null default 'pending'
    check (status in ('pending', 'reviewed', 'implemented', 'discarded')),
  note text not null default '',
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists feedback_notes_created_at_idx
  on public.feedback_notes (created_at desc);

create index if not exists feedback_notes_status_idx
  on public.feedback_notes (status);

create index if not exists feedback_notes_user_idx
  on public.feedback_notes (submitted_by_user_id);

alter table public.feedback_notes enable row level security;

create policy "public insert feedback notes"
on public.feedback_notes
for insert
to anon, authenticated
with check (true);

create policy "authenticated read own feedback notes"
on public.feedback_notes
for select
to authenticated
using (
  submitted_by_user_id = auth.uid()
  or submitted_by_email = coalesce(auth.jwt() ->> 'email', '')
);

create policy "service role manage feedback notes"
on public.feedback_notes
for all
to service_role
using (true)
with check (true);

comment on table public.feedback_notes is
  'Notas libres de feedback e ideas de producto enviadas desde la app para revisar, priorizar e implementar luego.';
