-- Migracion aditiva de horarios v2
-- Ejecutar sobre una base que ya tenga:
--   public.spots
--   public.spot_branches
--
-- Esto agrega la estructura correcta para horarios semanales y excepciones,
-- manteniendo `spot_branches.hours` como campo editorial/derivado mientras
-- admin y app terminan de migrar.

alter table public.spot_branches
  add column if not exists holiday_mode text not null default 'inherit'
    check (holiday_mode in ('inherit', 'same_as_sunday', 'closed', 'custom'));
alter table public.spot_branches
  add column if not exists holiday_open_time time;
alter table public.spot_branches
  add column if not exists holiday_close_time time;
alter table public.spot_branches
  add column if not exists holiday_split_open_time time;
alter table public.spot_branches
  add column if not exists holiday_split_close_time time;

create table if not exists public.spot_branch_hours (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.spot_branches (id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  is_closed boolean not null default false,
  open_time time,
  close_time time,
  split_open_time time,
  split_close_time time,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, day_of_week)
);

create index if not exists spot_branch_hours_branch_idx on public.spot_branch_hours (branch_id);
create index if not exists spot_branch_hours_day_idx on public.spot_branch_hours (day_of_week);

create table if not exists public.spot_branch_schedule_exceptions (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.spot_branches (id) on delete cascade,
  exception_date date not null,
  is_closed boolean not null default false,
  open_time time,
  close_time time,
  split_open_time time,
  split_close_time time,
  label text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, exception_date)
);

create index if not exists spot_branch_schedule_exceptions_branch_idx
  on public.spot_branch_schedule_exceptions (branch_id);
create index if not exists spot_branch_schedule_exceptions_date_idx
  on public.spot_branch_schedule_exceptions (exception_date);

alter table public.spot_branch_hours replica identity full;
alter table public.spot_branch_schedule_exceptions replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'spot_branch_hours'
  ) then
    execute 'alter publication supabase_realtime add table public.spot_branch_hours';
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'spot_branch_schedule_exceptions'
  ) then
    execute 'alter publication supabase_realtime add table public.spot_branch_schedule_exceptions';
  end if;
end $$;

-- Si quieres inicializar una base vacia de horario semanal para sedes existentes,
-- descomenta este bloque. Crea Lun-Dom abiertos en null para edición posterior.
--
-- insert into public.spot_branch_hours (branch_id, day_of_week, is_closed, sort_order)
-- select branch.id, day.day_of_week, false, day.day_of_week
-- from public.spot_branches branch
-- cross join (
--   values (0), (1), (2), (3), (4), (5), (6)
-- ) as day(day_of_week)
-- where not exists (
--   select 1
--   from public.spot_branch_hours existing
--   where existing.branch_id = branch.id
--     and existing.day_of_week = day.day_of_week
-- );
